### ISSUE TITLE
Test wechaty basic functions

### ISSUE THREAD

**Issue by lijiarui** [lijiarui/wechaty-puppet-padchat#60]
- [x] contact-bot.ts
    - [x] https://github.com/Chatie/wechaty/issues/1319
    - [x] https://github.com/Chatie/wechaty/issues/1320
    - [x] https://github.com/Chatie/wechaty/issues/1321
    - [x] https://github.com/Chatie/wechaty/issues/1332
 - [x] ding-dong-bot.ts
 - [x] friend-bot.ts
    - [x] https://github.com/Chatie/wechaty/issues/1322
 - [ ] media-file-bot.ts
   - [ ] cannot save excel file https://github.com/Chatie/wechaty/issues/1349
   - [ ] cannot save voice to mp3 but slk
 - [x] room-bot.ts #63
    - [x] room-leave event: https://github.com/Chatie/wechaty/issues/1323
    - [x] room-leave event: https://github.com/Chatie/wechaty/issues/1329
    - [x] room-join-event:   https://github.com/Chatie/wechaty/issues/1324
    - [x] room-topic-event:  https://github.com/Chatie/wechaty/issues/1330
    - [x] room-topic-event:  https://github.com/Chatie/wechaty/issues/1326
    - [x] room join action
    - [x] kick off action
    - [x] create action: https://github.com/Chatie/wechaty/issues/1327
    - [x] https://github.com/Chatie/wechaty/issues/1328
-  [x] self-testing-bot.ts
- [ ] speech-to-text-bot

**Comment by lijiarui** [comment]
add quit-bot to `room-bot`

add the folloiwng to `rom-bot`
```ts
if (dingRoom.has(sender)) {
            /**
             * speaker is already in room
             */
            log.info('Bot', 'onMessage: sender has already in dingRoom')
            dingRoom.say('no need to ding again, because you are already in ding room', sender)
            // sendMessage({
            //   content: 'no need to ding again, because you are already in ding room'
            //   , to: sender
            // })

          } else {
```

**Comment by lijiarui** [comment]
add quit-bot to `room-bot`

add the folloiwng to `rom-bot`
```ts
if (dingRoom.has(sender)) {
            /**
             * speaker is already in room
             */
            log.info('Bot', 'onMessage: sender has already in dingRoom')
            dingRoom.say('no need to ding again, because you are already in ding room', sender)
            // sendMessage({
            //   content: 'no need to ding again, because you are already in ding room'
            //   , to: sender
            // })

          } else {
```

**Comment by zixia** [comment]
```diff
- if (dingRoom.has(sender)) {
+ if (await dingRoom.has(sender)) {
```

**Comment by lijiarui** [comment]
more room but:
 - [ ] Chatie/wechaty#1329
 - [ ] Chatie/wechaty#1343
 - [ ] Chatie/wechaty#1342
 - [ ] Chatie/wechaty#1339

**Comment by lijiarui** [comment]
done
