### ISSUE TITLE
Padchat known bugs

### ISSUE THREAD

**Issue by windmemory** [lijiarui/wechaty-puppet-padchat#97]
- [ ] [`Room.findAll()` returns 0 result when some room has no id](https://github.com/lijiarui/wechaty-puppet-padchat/issues/96)
- [ ] [Payload is not returned when calling getWXContact, when this happened and how to deal with this?](https://github.com/lijiarui/wechaty-puppet-padchat/issues/81)
- [ ] [Room/Friendship event support for Wechat Account in Languages other than English/Simple Chinese](https://github.com/lijiarui/wechaty-puppet-padchat/issues/78)
- [ ] [Memory usage issue, needs to consider redesign the method](https://github.com/Chatie/wechaty/issues/1459)
- [ ] [No response after run several hours](https://github.com/Chatie/wechaty/issues/1443)
- [ ] [Race Condition: discarded message because puppet is not logged-in](https://github.com/Chatie/wechaty/issues/1434)

**Comment by lijiarui** [comment]
> Room/Friendship event support for Wechat Account in Languages other than English/Simple Chinese

No need to support this at this period. This should be an enhancement part.

**Comment by lijiarui** [comment]
How is this issue going? @windmemory
